export const trending = [
      {
        "vote_average": 7.2,
        "id": 464052,
        "overview": "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
        "release_date": "2020-12-16",
        "adult": false,
        "backdrop_path": "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
        "genre_ids": [
          14,
          28,
          12
        ],
        "vote_count": 2516,
        "original_language": "en",
        "original_title": "Wonder Woman 1984",
        "poster_path": "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        "title": "Wonder Woman 1984",
        "video": false,
        "popularity": 4652.913,
        "media_type": "movie"
      },
      {
        "backdrop_path": "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
        "id": 508442,
        "genre_ids": [
          16,
          35,
          18,
          10402,
          14
        ],
        "original_language": "en",
        "original_title": "Soul",
        "poster_path": "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
        "video": false,
        "vote_average": 8.4,
        "overview": "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
        "release_date": "2020-12-25",
        "vote_count": 3299,
        "title": "Soul",
        "adult": false,
        "popularity": 4117.551,
        "media_type": "movie"
      },
      {
        "genre_ids": [
          28,
          53,
          878
        ],
        "original_language": "en",
        "original_title": "Tenet",
        "poster_path": "/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
        "title": "Tenet",
        "id": 577922,
        "overview": "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
        "release_date": "2020-08-22",
        "vote_count": 3834,
        "vote_average": 7.3,
        "adult": false,
        "backdrop_path": "/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
        "video": false,
        "popularity": 1299.013,
        "media_type": "movie"
      },
      {
        "adult": false,
        "backdrop_path": "/izNpxVcjKbF9BiYF4GVqxCOfewL.jpg",
        "genre_ids": [
          18
        ],
        "id": 641662,
        "original_language": "en",
        "original_title": "Pieces of a Woman",
        "overview": "When a young mother's home birth ends in unfathomable tragedy, she begins a year-long odyssey of mourning that fractures relationships with loved ones in this deeply personal story of a woman learning to live alongside her loss.",
        "poster_path": "/OgUfLlhfBFx5BPK6LzBWFvBW1w.jpg",
        "release_date": "2020-12-30",
        "title": "Pieces of a Woman",
        "video": false,
        "vote_average": 7,
        "vote_count": 148,
        "popularity": 159.879,
        "media_type": "movie"
      },
      {
        "vote_average": 5.9,
        "id": 614911,
        "overview": "A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.",
        "release_date": "2020-12-10",
        "adult": false,
        "backdrop_path": "/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg",
        "genre_ids": [
          18,
          878
        ],
        "vote_count": 861,
        "original_language": "en",
        "original_title": "The Midnight Sky",
        "poster_path": "/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg",
        "title": "The Midnight Sky",
        "video": false,
        "popularity": 1853.686,
        "media_type": "movie"
      },
      {
        "vote_average": 7.8,
        "id": 529203,
        "overview": "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
        "release_date": "2020-11-25",
        "adult": false,
        "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
        "genre_ids": [
          12,
          14,
          10751,
          16
        ],
        "vote_count": 1069,
        "original_language": "en",
        "original_title": "The Croods: A New Age",
        "poster_path": "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
        "title": "The Croods: A New Age",
        "video": false,
        "popularity": 1624.107,
        "media_type": "movie"
      },
      {
        "vote_average": 6.1,
        "id": 675327,
        "overview": "A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.",
        "release_date": "2020-12-31",
        "adult": false,
        "backdrop_path": "/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg",
        "genre_ids": [
          28,
          18,
          27,
          10752
        ],
        "vote_count": 123,
        "original_language": "en",
        "original_title": "Shadow in the Cloud",
        "poster_path": "/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg",
        "title": "Shadow in the Cloud",
        "video": false,
        "popularity": 982.146,
        "media_type": "movie"
      },
      {
        "adult": false,
        "backdrop_path": "/mDLrSHK4VtWmxyidCcF2Dh8vxNR.jpg",
        "genre_ids": [
          53
        ],
        "id": 549514,
        "original_language": "en",
        "original_title": "Fatale",
        "overview": "A married man is tricked into a murder scheme by a female police detective.",
        "poster_path": "/9v43jAAfCYcQEgeMJ1H0rghN0of.jpg",
        "release_date": "2020-12-18",
        "title": "Fatale",
        "video": false,
        "vote_average": 6.1,
        "vote_count": 14,
        "popularity": 109.61,
        "media_type": "movie"
      },
      {
        "vote_average": 6.1,
        "title": "We Can Be Heroes",
        "overview": "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
        "release_date": "2020-12-25",
        "adult": false,
        "backdrop_path": "/UgNke0mMQhQdnX2hEu4cN83M0a.jpg",
        "genre_ids": [
          28,
          14,
          10751
        ],
        "vote_count": 216,
        "original_language": "en",
        "original_title": "We Can Be Heroes",
        "poster_path": "/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg",
        "id": 615677,
        "video": false,
        "popularity": 1356.722,
        "media_type": "movie"
      },
      {
        "genre_ids": [
          28,
          53,
          80,
          18
        ],
        "original_language": "en",
        "original_title": "Honest Thief",
        "poster_path": "/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
        "title": "Honest Thief",
        "id": 553604,
        "overview": "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
        "release_date": "2020-09-03",
        "vote_count": 435,
        "vote_average": 6.7,
        "adult": false,
        "backdrop_path": "/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg",
        "video": false,
        "popularity": 1428.921,
        "media_type": "movie"
      },
      {
        "vote_average": 7.1,
        "title": "Greenland",
        "overview": "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
        "release_date": "2020-07-29",
        "adult": false,
        "backdrop_path": "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
        "genre_ids": [
          28,
          53
        ],
        "vote_count": 1312,
        "original_language": "en",
        "original_title": "Greenland",
        "poster_path": "/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
        "id": 524047,
        "video": false,
        "popularity": 1217.311,
        "media_type": "movie"
      },
      {
        "adult": false,
        "backdrop_path": "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
        "genre_ids": [
          12,
          28,
          878
        ],
        "original_language": "en",
        "original_title": "Star Wars",
        "poster_path": "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        "video": false,
        "vote_average": 8.2,
        "vote_count": 14898,
        "overview": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
        "id": 11,
        "title": "Star Wars",
        "release_date": "1977-05-25",
        "popularity": 136.575,
        "media_type": "movie"
      },
      {
        "backdrop_path": "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        "id": 299534,
        "genre_ids": [
          12,
          878,
          28
        ],
        "original_language": "en",
        "original_title": "Avengers: Endgame",
        "poster_path": "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
        "video": false,
        "vote_average": 8.3,
        "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        "release_date": "2019-04-24",
        "vote_count": 16260,
        "title": "Avengers: Endgame",
        "adult": false,
        "popularity": 209.626,
        "media_type": "movie"
      },
      {
        "overview": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
        "release_date": "2001-12-18",
        "adult": false,
        "backdrop_path": "/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg",
        "genre_ids": [
          12,
          14,
          28
        ],
        "vote_count": 18385,
        "original_language": "en",
        "original_title": "The Lord of the Rings: The Fellowship of the Ring",
        "poster_path": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        "video": false,
        "id": 120,
        "vote_average": 8.3,
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "popularity": 93.033,
        "media_type": "movie"
      },
      {
        "overview": "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
        "release_date": "2001-11-16",
        "adult": false,
        "backdrop_path": "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
        "genre_ids": [
          12,
          14
        ],
        "vote_count": 19264,
        "original_language": "en",
        "original_title": "Harry Potter and the Philosopher's Stone",
        "poster_path": "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
        "video": false,
        "id": 671,
        "vote_average": 7.9,
        "title": "Harry Potter and the Philosopher's Stone",
        "popularity": 183.514,
        "media_type": "movie"
      },
      {
        "overview": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
        "id": 340102,
        "adult": false,
        "backdrop_path": "/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg",
        "genre_ids": [
          28,
          27,
          878
        ],
        "vote_count": 1324,
        "original_language": "en",
        "original_title": "The New Mutants",
        "poster_path": "/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg",
        "title": "The New Mutants",
        "video": false,
        "vote_average": 6.4,
        "release_date": "2020-08-26",
        "popularity": 388.88,
        "media_type": "movie"
      },
      {
        "vote_average": 7.1,
        "id": 337401,
        "overview": "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
        "release_date": "2020-09-04",
        "adult": false,
        "backdrop_path": "/qAKvUu2FSaDlnqznY4VOp5PmjIF.jpg",
        "genre_ids": [
          12,
          14
        ],
        "vote_count": 3956,
        "original_language": "en",
        "original_title": "Mulan",
        "poster_path": "/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
        "title": "Mulan",
        "video": false,
        "popularity": 511.888,
        "media_type": "movie"
      },
      {
        "genre_ids": [
          53,
          27,
          18
        ],
        "original_language": "en",
        "original_title": "Run",
        "poster_path": "/mtDYMa2inpJjxq2DjELPXbtf02v.jpg",
        "title": "Run",
        "id": 546121,
        "overview": "Chloe, a teenager who is confined to a wheelchair, is homeschooled by her mother, Diane. Chloe soon becomes suspicious of her mother and begins to suspect that she may be harboring a dark secret.",
        "release_date": "2020-11-20",
        "vote_count": 320,
        "vote_average": 7.6,
        "adult": false,
        "backdrop_path": "/DnjwdbjdR2c5MFhKv5ZSRf8rDU.jpg",
        "video": false,
        "popularity": 82.287,
        "media_type": "movie"
      },
      {
        "overview": "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
        "release_date": "2020-10-25",
        "adult": false,
        "backdrop_path": "/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg",
        "genre_ids": [
          14,
          10751,
          12,
          35,
          27
        ],
        "vote_count": 1111,
        "original_language": "en",
        "original_title": "Roald Dahl's The Witches",
        "poster_path": "/b1C0FuXp4wiPmHLVKq4kwtDMgK6.jpg",
        "video": false,
        "id": 531219,
        "vote_average": 6.8,
        "title": "Roald Dahl's The Witches",
        "popularity": 498.88,
        "media_type": "movie"
      },
      {
        "vote_average": 7.4,
        "title": "Promising Young Woman",
        "overview": "A young woman haunted by a tragedy in her past takes revenge on the predatory men unlucky enough to cross her path.",
        "release_date": "2020-12-13",
        "adult": false,
        "backdrop_path": "/7bjFGAK9aEiMQ9nUhanoNDsnV8h.jpg",
        "genre_ids": [
          53,
          80,
          18
        ],
        "vote_count": 48,
        "original_language": "en",
        "original_title": "Promising Young Woman",
        "poster_path": "/cjzU4g6SlScnP4MdkleyI25KGlR.jpg",
        "id": 582014,
        "video": false,
        "popularity": 56.727,
        "media_type": "movie"
      }
]